### ISSUE TITLE
"Permission Denied" when cloning repo on Dropbox

### ISSUE THREAD

**Issue by kbjarkefur** [kbjarkefur/GitHubDropBox#1]
Originally posted by @eatorange in the private repository this tutorial was first developed in.
__________

Hi @kbjarkefur 
I am having a trouble in cloning a repo on Dropbox using Git Bash. Whenever I try to clone it as below, it does NOT ask me Github credential, but displays "_Permission Denied_" error message as below.

```
Seungmin Lee@DESKTOP-L3F0LNA MINGW64 ~/Documents/Github
$ cd ~/Dropbox

Seungmin Lee@DESKTOP-L3F0LNA MINGW64 ~/Dropbox
$ cd GitHubDropBoxTest_Min

Seungmin Lee@DESKTOP-L3F0LNA MINGW64 ~/Dropbox/GitHubDropBoxTest_Min
$ git clone https://github.com/eatorange/DropBoxGitHub_Min_Test.git
Cloning into 'DropBoxGitHub_Min_Test'...
C:/Users/Seungmin Lee/Dropbox/GitHubDropBoxTest_Min/DropBoxGitHub_Min_Test/.git: Permission denied
Deletion of directory 'DropBoxGitHub_Min_Test/.git' failed. Should I try again? (y/n) n
Deletion of directory 'DropBoxGitHub_Min_Test/.git' failed. Should I try again? (y/n) n
```

I haven't tried using another method to clone repo yet (ex. SSH), as I wanted to raise the issue that this error can also occur to other users.
I can try different things and update if it works, but this is still something we need to deal with.

Thank you!

**Comment by kbjarkefur** [comment]
Thanks @eatorange ! Yes, this is important that we figure out what is going on and provide helpful links.

That's strange. I was able to clone your fork. 
```
kbrkb@LAPTOP-9G1A84M0 MINGW64 ~/Documents/GitHub
$ git clone https://github.com/eatorange/DropBoxGitHub_Min_Test.git
Cloning into 'DropBoxGitHub_Min_Test'...
remote: Counting objects: 6, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 6 (delta 0), reused 6 (delta 0), pack-reused 0
Unpacking objects: 100% (6/6), done.
```

I know you are busy, so only do this when you have time, but can you test the following when you have a chance.

1. Can you try to clone to a folder that does **not** have a space in the file path as in "C:/Users/**Seungmin Lee**/Dropbox"? I do not know if this should make a difference, but spaces in file paths is always a good place to start.
1. Can you try to clone https://github.com/kbjarkefur/DropBoxGitHubTest.git without making a fork from it? (This is a _private_ repo you are added to)
1. Can you try to clone https://github.com/kbjarkefur/GitHubDropBox.git without making a fork from it? (This is a _public_ repo)

This will help me understand if there is something with your fork or if this is something related to your set up of Git Bash. 

Thanks again!

**Comment by mrimal** [comment]
Thanks @eatorange. Also, if you are still having problems, 

I have a couple more suggestions to the problem. I was able to recreate the problem and successfully solve it on my machine. Please try : 

1) Running the same commands on a different directory. Maybe the directory you have does not have write access and hence you're running into the problem.

2) If the problem still persists, try right clicking on the bash window and running it as admin. This should solve maybe some other problems you might have. If that doesn't work, then there is a config problem with your bash, which I can look at when I next see you!

Thanks a lot, @eatorange.

**Comment by eatorange** [comment]
Thanks @kbjarkefur and @mrimal !

I have tried a couple of approaches you suggested, and here's what I found.

- Spaces in file path is **NOT** the reason, as I was able to clone repository in a different path with space.
- Type of repository (private/public) is **NOT** the reason, as I was able to clone both private and public repo in a different path (I was asked to enter my Github credential when cloning private repo)
- Running as an admin did **NOT** solve the issue
- I assume it has something do to with Windows folder permissions, it is because
  - I was able to clone repos under "C:/"
  - I was able to clone repos under "C:/Users/(username)/Documents"
  - I was **NOT** able to clone repos under "C:/Users". I got the error message (_fatal: could not create work tree dir 'DropBoxGitHubTest': Permission denied_)
  - I was **NOT** able to clone repos under "C:/Users/(username)/Documents/Github". (same _"permission denied_" error message I initially reported, **NOT** the one starting with "_could not create..._"I just reported above) This is quite strange as I have cloned most working repos in this path using Github for Desktop app.
  - I was **NOT** able to clone repos under "C:/Users/(username)/Dropbox"

This is all I found for now.
Please let me know if you have any ideas.

Thanks again!

**Comment by kbjarkefur** [comment]
This is really great feed back! thanks! But it leaves me really confused. I will look into this as soon as possible and then get back to you. 

Which command line interface are you using? It is GitBash right?

**Comment by eatorange** [comment]
Yes I am using Git Bash.

**Comment by kbjarkefur** [comment]
@eatorange , here is something that might give us a clue. The command `icacls` does nothing but listing the permissions to a folder or a file for all the different user created and built in user accounts.  Can you do the two steps below and reply with the output from both of them?

First step, do this for the DropBox folder where you were **not** able to clone the repo
```
icacls "C:/Users/(username)/Dropbox"
```
Second step, do this for another folder where you were able to clone the repo, for example _/Documents_
```
icacls "C:/Users/(username)/Documents"
```
You should get output that looks like this:
```
kbrkb@LAPTOP-9G1A84M0 MINGW64 ~/Documents/GitHub
$ icacls "C:\Users\kbrkb\Dropbox"
C:\Users\kbrkb\Dropbox NT AUTHORITY\SYSTEM:(OI)(CI)(F)
                       BUILTIN\Administrators:(OI)(CI)(F)
                       LAPTOP-9G1A84M0\kbrkb:(OI)(CI)(F)
```
Thanks!

**Comment by eatorange** [comment]
Hi @kbjarkefur 

Here's what I did as you suggested and results.

* Folders which I was able to clone ("C:/", "C:/Users/(username)")
```
Seungmin Lee@DESKTOP-L3F0LNA MINGW64 ~
$ icacls "C:/"
C:/ BUILTIN\Administrators:(OI)(CI)(F)
    NT AUTHORITY\SYSTEM:(OI)(CI)(F)
    BUILTIN\Users:(OI)(CI)(RX)
    NT AUTHORITY\Authenticated Users:(OI)(CI)(IO)(M)
    NT AUTHORITY\Authenticated Users:(AD)
    Mandatory Label\High Mandatory Level:(OI)(NP)(IO)(NW)
```

```
Seungmin Lee@DESKTOP-L3F0LNA MINGW64 ~
$ icacls "C:/Users/Seungmin Lee"
C:/Users/Seungmin Lee NT AUTHORITY\SYSTEM:(OI)(CI)(F)
                      BUILTIN\Administrators:(OI)(CI)(F)
                      DESKTOP-L3F0LNA\Seungmin Lee:(OI)(CI)(F)
```

* Folders which I couldn't clone ("C:/Users/(username)/Documents", "C:/Users/(username)/Documents/Github". "C:/Users/(username)/Dropbox")
_Last time I reported "/Documents" folder was working, but today it is NOT. Maybe I reported wrong or something changed._

```
Seungmin Lee@DESKTOP-L3F0LNA MINGW64 /c/Users
$ icacls "C:/Users"
C:/Users NT AUTHORITY\SYSTEM:(OI)(CI)(F)
         BUILTIN\Administrators:(OI)(CI)(F)
         BUILTIN\Users:(RX)
         BUILTIN\Users:(OI)(CI)(IO)(GR,GE)
         Everyone:(RX)
         Everyone:(OI)(CI)(IO)(GR,GE)
```

```
Seungmin Lee@DESKTOP-L3F0LNA MINGW64 ~/Documents
$ icacls "C:/Users/Seungmin Lee/Documents"
C:/Users/Seungmin Lee/Documents NT AUTHORITY\SYSTEM:(OI)(CI)(F)
                                BUILTIN\Administrators:(OI)(CI)(F)
                                DESKTOP-L3F0LNA\Seungmin Lee:(OI)(CI)(F)
                                NT AUTHORITY\SYSTEM:(I)(OI)(CI)(F)
                                BUILTIN\Administrators:(I)(OI)(CI)(F)
                                DESKTOP-L3F0LNA\Seungmin Lee:(I)(OI)(CI)(F)
```

```
Seungmin Lee@DESKTOP-L3F0LNA MINGW64 ~/Documents/Github
$ icacls "C:/Users/Seungmin Lee/Documents/Github"
C:/Users/Seungmin Lee/Documents/Github NT AUTHORITY\SYSTEM:(OI)(CI)(F)
                                       BUILTIN\Administrators:(OI)(CI)(F)
                                       DESKTOP-L3F0LNA\Seungmin Lee:(OI)(CI)(F)
```

```
Seungmin Lee@DESKTOP-L3F0LNA MINGW64 ~/Dropbox
$ icacls "C:/Users/Seungmin Lee/Dropbox"
C:/Users/Seungmin Lee/Dropbox NT AUTHORITY\SYSTEM:(OI)(CI)(F)
                              BUILTIN\Administrators:(OI)(CI)(F)
                              DESKTOP-L3F0LNA\Seungmin Lee:(OI)(CI)(F)
```


It is strange that it gives the same message for the working folder (/(username) and non-working folder (/Github, /Dropbox).... Maybe it's not a matter of permission?

**Comment by kbjarkefur** [comment]
Hmmm.... :confused:

Ok, let's try this next. `git clone` is actually a short hand for the four commands commands `mkdir`, `git init`, `git remote add` and `git pull`. Let's do those in order an let's see where it breaks down. So do these steps in order:

```
# Go to a folder where you are not able to clone
cd "C:/Users/Seungmin Lee/Dropbox"

# Create the folder for the repository and move into it (you may call the folder something else)
mkdir GitHubDropBox
cd GitHubDropBox

# Set up an empty clone
git init

# Connect this clone to the repository we are cloning
git remote add origin https://github.com/kbjarkefur/GitHubDropBox.git

# Get all the commits that already exist in the repo
git pull origin master
```
Let me know if this works or if you get some errors.

Thanks @eatorange

**Comment by eatorange** [comment]
Hey @kbjarkefur 

I followed the steps above. I was able to create folder, but got the error when I was creating an empty repo via `git init`.
```
$ git init
C:/Users/Seungmin Lee/Dropbox/GitTest/.git: Permission denied
```
When I re-typed `git init`, I got slightly different error message as below

```
$ git init
fatal: cannot copy 'C:\Program Files\Git\mingw64/share/git-core/templates/description' to 'C:/Users/Seungmin Lee/Dropbox/GitTest/.git/description': Permission denied
```

So it seems there's an error in copying files to certain folder.
Hope this information helps.

**Comment by kbjarkefur** [comment]
This might be interesting:
> $ git init
> fatal: cannot copy 'C:\Program Files\Git\mingw64/share/git-core/templates/description' to 'C:/Users/Seungmin Lee/Dropbox/GitTest/.git/description': Permission denied

See how the beginning of the first file path has backward slashes. Git Bash usually only likes forward slashes. I will look into this.

Don't explain the first `git init` error and how you get different errors, but we might be on to something.

**Comment by eatorange** [comment]
I am not sure whether that's the problem. If backward slashes in the origin file path were the problem, then I shouldn't be able to create repo to any directory. But as you know I can still create an empty repo in certain directories.
Maybe I can un-install and re-install git and see if it works. I will try that later.

**Comment by kbjarkefur** [comment]
I was thinking that you would have to reinstall as well, but I wanted to explore so we were more certain of what was wrong.

I do not think that different folders should matter either, but just as you have folder globals in Stata, windows have PATH globals, and different applications overrides different paths to different folders they need access to. So say that an installation of Python overrides the path to DropBox. Exactly that is not likely, but I am learning as I go here, so I do not know the details yet. But I have learned a ton so far working on this issue. 😄

**Comment by kbjarkefur** [comment]
Actually, can you try this. In `git init` you can specify the folder were the repository template is copied from and where it should be copied to. This should not rely on any path globals. This I think should be the definitive test that it has nothing to do with incorrect slashes in the folder path.

```
git init --template="C:/Program Files/Git/mingw64/share/git-core/templates" "C:/Users/Seungmin Lee/Dropbox/GitTest/"
```

Make sure that is the path on your computer to the _git-core/templates_ and that the second path is a folder where you want to create the clone.

**Comment by eatorange** [comment]
I am getting the same error message as below, which means slash is NOT the problem.

```
$ git init --template="C:/Program Files/Git/mingw64/share/git-core/templates" "C:/Users/Seungmin Lee/Dropbox/GitTest/"
C:/Users/Seungmin Lee/Dropbox/GitTest/.git: Permission denied
```

**Comment by kbjarkefur** [comment]
ok, thanks for testing everything I asked you to test anyways.

Maybe re-installing _git bash_ is the best thing we can do now.

**Comment by eatorange** [comment]
I just un- and re-installed Git, but it is still NOT working with Git Bash.

One thing I found is that I was ABLE to clone using Windows Powershell, thus at least now we know that it is a Git-Bash-related problem.

**Comment by kbjarkefur** [comment]
ok, can you test if you can still do `git pull` with git bash? 

If it was this repo that you cloned I can do an update that you then can pull.

You can also test if `git status` works in git bash.

**Comment by kbjarkefur** [comment]
what version of git are you using? type `git --version` in git bash

**Comment by eatorange** [comment]
`Git status` works, and my version is 2.16.1.windows.4.

I cloned this repo to my laptop (where I could clone), made a random commit to the remote from another system (WB PC), and pulled that commit from remote to my laptop. `git pull` works with git bash as well.

**Comment by eatorange** [comment]
@kbjarkefur @mrimal 

Guys I finally found why - it was **Bitdefender** installed in my laptop.

![bitdefender_protected_folders](https://user-images.githubusercontent.com/12057345/36308609-61d76408-12ef-11e8-9fc2-437750311e52.jpg)
![bitdefender_app_access](https://user-images.githubusercontent.com/12057345/36308608-61c40db8-12ef-11e8-9066-c90da0d5166a.jpg)


In the first screenshot, it shows the list of folders Bitdefender protects. As stated, access to those folders are limited and only trusted applications can make changes. You can see _Dropbox_ folder is one of them.
In the second screenshot, "Git for Windows" was _blocked_ - thus unable to copy files to my protected folders - including Dropbox folder. I changed Git's access level to "allowed", and then I was able to clone a repo on the folder. This also explains why I was able to clone repo via powershell, but not via Git Bash.


I recognized once again that Bitdefender is a super pick app...

**Comment by kbjarkefur** [comment]
Great work @eatorange ! This is really useful information!
